##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hrgshcycdsm0/public_html/tigon.balcomsoft.com/documentation/
- /bin/cp -R * $DEPLOYPATH